name: Master Build

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  slack-workflow-status:
    name: Post workflow status to Slack
    needs:
      - ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we need to notify
        uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          branch: master
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack workflow notification
        uses: Gamesight/slack-workflow-status@master
        if: steps.should_notify.outputs.should_send_message == 'yes'
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: 'creator-deployments'
          name: "ansible-fastly"